name: Earth2FA
version: "0.0.02"
api-version: 1.16
authors: [ItchyDitchy]
main: net.earthnetwork.earth2fa.Earth2FAPlugin
description: Another layer of protection for a server.
softdepend: [SuperiorSkyblock2, PlaceholderAPI, Vault, PermissionsEX, LuckPerms]

commands:
  2fa:
    description: Main 2FA Command
    aliases: [auth, authenticator, earthauth, earthauthenticator, earth2fa, e2fa]

permissions:
  earth2fa.use:
    default: op
  earth2fa.auth:
    default: op
  earth2fa.unregister:
    default: op
  earth2fa.reload:
    default: op