name: Earth2FA
version: "0.0.01"
api-version: 1.16
authors: [ItchyDitchy]
main: net.earthnetwork.earth2fa.Earth2FAPlugin
description: Another layer of protection for a serer.
softdepend: [PlaceholderAPI, Vault, PermissionsEX, LuckPerms]

commands:
  2fa:
    description: Main 2FA Command
    aliases: [auth]

permissions:
  2fa.staff:
    description: The staff permission for the plugin.
    default: op